/// Flutter icons ChordLogCustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChordLogCustomIcons
///      fonts:
///       - asset: fonts/ChordLogCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ChordLogCustomIcons {
  ChordLogCustomIcons._();

  static const _kFontFam = 'ChordLogCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData progression = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eight_silent_note = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eighth_note = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData half_note = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progression_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quarter_note = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quarter_silent_note = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sixteenth_note = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sixteenth_silent_note = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thirty_second_note = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thirty_second_silent_note = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whole_note = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chord = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
